import os
SQLALCHEMY_DATABASE_URI = 'sqlite:///%s/datastore.db' % (os.path.dirname(__file__))

SQLALCHEMY_POOL_RECYCLE = 3600
SQLALCHEMY_TRACK_MODIFICATIONS = False

RECAPTCHA_PUBLIC_KEY ="6LcmmQcUAAAAABVWGc0kN1AfncL4x0zWyJeV861b"
RECAPTCHA_PRIVATE_KEY = "6LcmmQcUAAAAAKEvAgPie_qV1IRkouBgz4R2evrd"

WTF_CSRF_ENABLED = True
SECRET_KEY = 'Ws$DFJi!fuAhS*rgY'
